"""Baseline NFL position importance weights for draft-board calculations."""


POSITION_IMPORTANCE = (
    {
        "position_code": "QB",
        "display_name": "Quarterback",
        "importance_score": 100,
        "weighting_version": "baseline-2026-v1",
        "rationale": "Quarterback has the greatest direct influence on offensive operation and team value.",
    },
    {
        "position_code": "EDGE",
        "display_name": "Edge Rusher",
        "importance_score": 92,
        "weighting_version": "baseline-2026-v1",
        "rationale": "Premium pass-rush impact affects pressure, sacks, and defensive disruption.",
    },
    {
        "position_code": "OT",
        "display_name": "Offensive Tackle",
        "importance_score": 90,
        "weighting_version": "baseline-2026-v1",
        "rationale": "Protects the quarterback and supports efficient offensive execution.",
    },
    {
        "position_code": "CB",
        "display_name": "Cornerback",
        "importance_score": 88,
        "weighting_version": "baseline-2026-v1",
        "rationale": "Coverage quality limits explosive passing plays and defensive matchup stress.",
    },
    {
        "position_code": "WR",
        "display_name": "Wide Receiver",
        "importance_score": 84,
        "weighting_version": "baseline-2026-v1",
        "rationale": "Creates separation and explosive receiving value in modern offenses.",
    },
    {
        "position_code": "DT",
        "display_name": "Defensive Tackle",
        "importance_score": 82,
        "weighting_version": "baseline-2026-v1",
        "rationale": "Interior disruption affects both pass rush and run defense.",
    },
    {
        "position_code": "IOL",
        "display_name": "Interior Offensive Line",
        "importance_score": 78,
        "weighting_version": "baseline-2026-v1",
        "rationale": "Interior protection and blocking support offensive consistency.",
    },
    {
        "position_code": "TE",
        "display_name": "Tight End",
        "importance_score": 68,
        "weighting_version": "baseline-2026-v1",
        "rationale": "Provides receiving versatility and formation flexibility.",
    },
    {
        "position_code": "LB",
        "display_name": "Linebacker",
        "importance_score": 65,
        "weighting_version": "baseline-2026-v1",
        "rationale": "Contributes to run defense, coverage, and second-level communication.",
    },
    {
        "position_code": "S",
        "display_name": "Safety",
        "importance_score": 60,
        "weighting_version": "baseline-2026-v1",
        "rationale": "Provides coverage range, run support, and pre-snap flexibility.",
    },
    {
        "position_code": "RB",
        "display_name": "Running Back",
        "importance_score": 48,
        "weighting_version": "baseline-2026-v1",
        "rationale": "Has offensive value, but replacement and positional volatility reduce baseline priority.",
    },
    {
        "position_code": "FB",
        "display_name": "Fullback",
        "importance_score": 35,
        "weighting_version": "baseline-2026-v1",
        "rationale": "Situational offensive role with limited league-wide usage.",
    },
    {
        "position_code": "P",
        "display_name": "Punter",
        "importance_score": 20,
        "weighting_version": "baseline-2026-v1",
        "rationale": "Special-teams field-position value is important but less central to roster construction.",
    },
    {
        "position_code": "K",
        "display_name": "Kicker",
        "importance_score": 18,
        "weighting_version": "baseline-2026-v1",
        "rationale": "Scoring value matters, but the role has narrower roster impact than core positions.",
    },
    {
        "position_code": "LS",
        "display_name": "Long Snapper",
        "importance_score": 10,
        "weighting_version": "baseline-2026-v1",
        "rationale": "Specialized role with the narrowest baseline influence on draft value.",
    },
)